import {footer} from './layout.js';
import {matchesQuery,filterFaculty,validateSaved,buildEmail,prepareData} from './engine.js';
import {createViews,e,areas,url,date,ext,head,empty,lanePanel} from './views.js';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const params=()=>Object.fromEntries(new URLSearchParams(location.search));
const hero=$('.hero')?.outerHTML||$('#home-hero')?.innerHTML||'';
const state={saved:[],compare:[],storageAvailable:true};
let data={},views,toastTimer;
const collections=()=>({faculty:data.faculty,labs:data.labs,stories:data.stories});
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,4500);}
function persist(){try{localStorage.setItem('ut-science-saved-v1',JSON.stringify(state.saved));return true;}catch{state.storageAvailable=false;return false;}}
function updateSaved(){for(const b of $$('[data-save]')){const active=state.saved.includes(b.dataset.save);b.classList.toggle('is-saved',active);b.setAttribute('aria-pressed',String(active));$('span',b).textContent=active?'Saved':b.getAttribute('aria-label');}$('#saved-count').textContent=state.saved.length;}
function toggleSave(key){state.saved=state.saved.includes(key)?state.saved.filter(k=>k!==key):[...state.saved,key];const ok=persist();updateSaved();if(location.pathname==='/saved/')render();toast(ok?(state.saved.includes(key)?'Saved to your research notebook.':'Removed from your saved research.'):'Saved for this session only. Browser storage is unavailable.');}
function updateCompare(){for(const c of $$('[data-compare]'))c.checked=state.compare.includes(c.dataset.compare);$('#compare-tray').hidden=state.compare.length===0;$('#compare-count').textContent=state.compare.length;for(const b of $$('[data-show-compare]')){b.disabled=state.compare.length===0;if(!b.closest('#compare-tray'))b.textContent='Compare '+state.compare.length+' profiles →';}$('#compare-names').textContent=state.compare.map(id=>data.faculty.find(f=>f.id===id).name).join(' · ');}
function updateDirectory(){const r=views.directoryResults(params());$('#directory-count').textContent=r.count;$('#directory-results').innerHTML=r.html;updateSaved();updateCompare();}
function updateDiscoveries(){$('#discovery-results').innerHTML=views.discoveryResults(params());}
function updateStreams(){$('#stream-results').innerHTML=views.streamResults(params());}
function showDialog(title,html){const d=$('#main-dialog');if(d.open)d.close();$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=html;d.showModal();}
function compareDialog(){if(!state.compare.length){toast('Select up to three profiles using their Compare checkboxes.');return;}showDialog('Compare your research shortlist',views.comparison());}
function navigate(href,replace=false){const u=new URL(href,location.origin);if(u.pathname===location.pathname&&u.search===location.search&&u.hash){document.getElementById(decodeURIComponent(u.hash.slice(1)))?.scrollIntoView();document.getElementById(decodeURIComponent(u.hash.slice(1)))?.focus({preventScroll:true});history.pushState({},'',u);return;}history[replace?'replaceState':'pushState']({},'',u.pathname+u.search+u.hash);render();if(u.hash)requestAnimationFrame(()=>document.getElementById(decodeURIComponent(u.hash.slice(1)))?.scrollIntoView());else{window.scrollTo(0,0);$('#main').focus({preventScroll:true});}}
function setParams(p,callback){const u=new URL(location.href);u.search=new URLSearchParams(Object.entries(p).filter(([,v])=>v)).toString();history.replaceState({},'',u);callback();}
function render(){const p=location.pathname;const d=$('#main-dialog');if(d.open)d.close();const q=params();const fn=p==='/'?()=>views.home(hero):p==='/explore/'?()=>views.explore(q):p==='/areas/'?views.researchAreas:p==='/directory/'?()=>views.directory(q):(p.startsWith('/faculty/')||p.startsWith('/labs/'))?()=>views.detail(p.split('/')[2]):p==='/discoveries/'?()=>views.discoveries(q):p==='/pathways/'?()=>views.pathways(q):p==='/fri/'?()=>views.fri(q):p==='/resources/'?views.resources:p==='/contact-professor/'?()=>views.contact(q):p==='/saved/'?()=>views.savedPage(q):()=>head('PAGE NOT FOUND','Let’s find your way back.','<a href="/explore/">Explore research →</a>');$('#main').innerHTML=fn();if(p==='/directory/')updateDirectory();if(p==='/discoveries/')updateDiscoveries();if(p==='/fri/')updateStreams();updateSaved();updateCompare();for(const a of $$('nav a')){if(new URL(a.href).pathname===p)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');}document.title=p==='/'?'UT Science Research for Undergraduates':$('h1')?.innerText.replace(/\s+/g,' ')+' · UT Science Research';$('#navigation').classList.remove('open');$('.menu-toggle').setAttribute('aria-expanded','false');}
function events(){document.addEventListener('click',async ev=>{const a=ev.target.closest('a');if(a&&a.origin===location.origin&&!a.pathname.startsWith('/data/')&&!a.target&&!ev.ctrlKey&&!ev.metaKey&&!ev.shiftKey&&!a.hasAttribute('download')){ev.preventDefault();navigate(a.href);return;}const b=ev.target.closest('button');if(!b)return;
if(b.matches('.menu-toggle')){const open=b.getAttribute('aria-expanded')!=='true';b.setAttribute('aria-expanded',String(open));$('#navigation').classList.toggle('open',open);}
if(b.id==='saved-nav')navigate('/saved/');
if(b.dataset.save)toggleSave(b.dataset.save);
if(b.dataset.query)navigate(url('/explore/',{q:b.dataset.query}));
if(b.dataset.interest){$('#match-interest').value=b.dataset.interest;$$('.map-label').forEach(n=>n.classList.toggle('is-selected',n===b));toast(b.dataset.interest+' selected for your match.');}
if(b.hasAttribute('data-lane')){$$('[data-lane]').forEach(n=>{n.classList.toggle('selected',n===b);n.setAttribute('aria-pressed',String(n===b));});$('#lane-panel').innerHTML=lanePanel(Number(b.dataset.lane));}
if(b.dataset.scroll)$('.radar-track').scrollBy({left:Number(b.dataset.scroll)*380,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});
if(b.hasAttribute('data-share')){try{await navigator.clipboard.writeText(location.href);toast('Link copied with your current filters.');}catch{showDialog('Copy this filtered link',`<label class="filter-field">Shareable URL<input readonly value="${e(location.href)}"></label>`);}}
if(b.dataset.email){showDialog('A thoughtful first introduction',views.emailBuilder(b.dataset.email,'dialog'));}
if(b.hasAttribute('data-close-dialog'))$('#main-dialog').close();
if(b.hasAttribute('data-show-compare'))compareDialog();
if(b.hasAttribute('data-clear-compare')){state.compare=[];updateCompare();}
if(b.hasAttribute('data-open-filters')){const d=$('#filter-dialog');d.append($('.filter-panel'));d.showModal();d.addEventListener('close',()=>$('#filter-slot')?.append($('.filter-panel')),{once:true});}
if(b.hasAttribute('data-close-filters'))$('#filter-dialog').close();
if(b.hasAttribute('data-copy-draft')){const field=b.closest('form').querySelector('[data-email-draft]');if(!field.value){toast('Create your outline first.');return;}try{await navigator.clipboard.writeText(field.value);toast('Draft copied. Review and personalize it before sending.');}catch{field.focus();field.select();toast('Select and copy the draft using your keyboard.');}}
if(b.hasAttribute('data-about'))showDialog('About this website concept','<p>An independent discovery concept using publicly available UT sources. It is not an official UT website.</p><p>Profiles and stories are a reviewed snapshot, not a live feed. Saved items stay in your browser; email draft fields are not transmitted or stored by this site. Clearing browser storage removes saved items.</p><p>Image credits appear with stories; faculty portraits come from their linked official profiles.</p>');});
document.addEventListener('change',ev=>{const t=ev.target;if(t.dataset.compare){if(t.checked){if(state.compare.length===3){t.checked=false;toast('You can compare up to three profiles. Deselect one to add another.');return;}state.compare.push(t.dataset.compare);}else state.compare=state.compare.filter(id=>id!==t.dataset.compare);updateCompare();}if(t.closest('#directory-form')||t.id==='directory-sort'){const f=Object.fromEntries(new FormData($('#directory-form')));f.sort=$('#directory-sort').value;setParams(f,updateDirectory);}if(t.closest('#pathway-form')&&t.tagName==='SELECT')navigate(url('/pathways/',{major:t.value}));});
document.addEventListener('submit',ev=>{const f=ev.target;ev.preventDefault();const v=Object.fromEntries(new FormData(f));if(f.id==='search-form')navigate(url('/explore/',{q:v.search}));if(f.id==='explore-form')setParams(v,()=>$('#explore-results').innerHTML=views.exploreResults(v.q));if(f.id==='match-form'){const area=$('#match-interest').value,goal=$('#match-goal').value,experience=$('#match-experience').value;const matching=data.pathways.filter(p=>p.area===area);showDialog('Your research pathways',`<p class="match-result-intro">${e(area)} · ${e(experience)} · ${e(goal)}</p><p>${experience==='Just starting'?'Start with an introductory program or read a few faculty profiles. You do not need prior research experience to explore.':experience==='Some coursework'?'Use a course or project you enjoyed as the starting point for your faculty shortlist.':'Connect your previous methods and questions to the next field you want to explore.'}</p><div class="resource-grid">${matching.map(p=>`<article><h3><a href="/pathways/?major=${p.id}">${e(p.name)} →</a></h3><p>${e(p.topics.join(' · '))}</p></article>`).join('')}</div><div class="dialog-actions"><a class="button orange" href="${goal==='Understand a paper'?'/discoveries/?view=publications':goal==='Present research'?'/resources/':goal==='Explore fields'?'/areas/':url('/directory/',{area})}">${goal==='Understand a paper'?'Explore publications':goal==='Present research'?'Prepare to present':goal==='Explore fields'?'Explore research areas':'Explore related faculty'} →</a>${experience==='Just starting'?'<a class="button outline" href="/fri/">Explore FRI</a>':''}</div>`);}
if(f.id==='directory-form'){v.sort=$('#directory-sort').value;if($('#filter-dialog')?.open)$('#filter-dialog').close();setParams(v,updateDirectory);}
if(f.id==='discovery-form')setParams({...v,view:params().view},updateDiscoveries);if(f.id==='stream-form')setParams(v,updateStreams);if(f.id==='pathway-form')navigate(url('/pathways/',v));if(f.hasAttribute('data-email-form')){const faculty=data.faculty.find(x=>x.id===v.faculty);f.querySelector('[data-email-draft]').value=buildEmail({...v,professor:faculty?.name||''});toast('Outline ready to edit.');}});
window.addEventListener('popstate',render);window.addEventListener('storage',ev=>{if(ev.key==='ut-science-saved-v1'){try{state.saved=validateSaved(JSON.parse(ev.newValue||'[]'),collections());if(location.pathname==='/saved/')render();else updateSaved();}catch{}}});}
function webTools(){if(!document.modelContext?.registerTool)return;const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});const register=t=>{try{Promise.resolve(document.modelContext.registerTool(t,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
register({name:'filter_research_directory',title:'Filter research directory',description:'Navigate to the faculty directory and apply topic, department, and area filters. Does not contact faculty.',inputSchema:{type:'object',properties:{query:{type:'string'},department:{type:'string'},area:{type:'string',enum:areas}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).some(k=>!['query','department','area'].includes(k))||Object.values(input).some(v=>typeof v!=='string')||(input.area&&!areas.includes(input.area)))throw new Error('Invalid directory filters');navigate(url('/directory/',{q:input.query,department:input.department,area:input.area}));return{count:filterFaculty(data.faculty,params()).length,url:location.href};}});
register({name:'save_research_items',title:'Save research items',description:'Save faculty, labs, or stories in this browser notebook. Does not email or contact anyone.',inputSchema:{type:'object',properties:{keys:{type:'array',items:{type:'string'},maxItems:30}},required:['keys'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||Object.keys(input).some(k=>k!=='keys')||!Array.isArray(input.keys)||input.keys.length>30||validateSaved(input.keys,collections()).length!==new Set(input.keys).size)throw new Error('Invalid saved research keys');state.saved=[...new Set([...state.saved,...input.keys])];const persisted=persist();updateSaved();if(location.pathname==='/saved/')render();return{savedCount:state.saved.length,persisted};}});}
async function init(){try{if(location.pathname==='/opportunities/')history.replaceState({},'', '/directory/');const names=['faculty','faculty_enrichment','faculty_sources','labs','research_stories','publications','pathways','streams','departments','resources','meta','catalog_audit'];await Promise.all(names.map(async n=>{const r=await fetch('/data/'+n+'.json');if(!r.ok)throw new Error('Source collection unavailable');data[n]=await r.json();}));data=prepareData(data);try{state.saved=validateSaved(JSON.parse(localStorage.getItem('ut-science-saved-v1')||'[]'),collections());}catch{state.saved=[];state.storageAvailable=false;}views=createViews(data,state);
$('#main').setAttribute('tabindex','-1');$('.brand').href='/';$('#navigation').innerHTML='<a href="/explore/">Explore research</a><a href="/directory/">Faculty & labs</a><a href="/discoveries/">Discoveries</a><a href="/resources/">Student guide</a><button class="saved-link" id="saved-nav">Saved <span id="saved-count">0</span></button>';
if(!$('.section-nav'))$('.site-header').insertAdjacentHTML('afterend','<nav class="section-nav wrap" aria-label="Research platform"><a href="/">Home</a><a href="/areas/">Research areas</a><a href="/discoveries/">Publications & discoveries</a><a href="/pathways/">Pathways by major</a><a href="/fri/">First-year research</a><a href="/contact-professor/">Contact a professor</a></nav>');
if(!$('footer'))$('#main').insertAdjacentHTML('afterend',footer());$('#main').insertAdjacentHTML('afterend','<div class="compare-tray" id="compare-tray" hidden><div><strong><span id="compare-count">0</span> / 3 profiles</strong><span id="compare-names"></span></div><button class="button light" data-show-compare>Compare interests →</button><button class="text-button" data-clear-compare>Clear</button></div><dialog class="main-dialog" id="main-dialog" aria-labelledby="dialog-title"><div class="dialog-heading"><h2 id="dialog-title"></h2><button data-close-dialog aria-label="Close dialog">×</button></div><div id="dialog-body"></div></dialog>');$('#loading-status')?.remove();$('#main').removeAttribute('aria-busy');events();render();webTools();}
catch(err){$('#main').innerHTML=head('RESEARCH COLLECTION UNAVAILABLE','We couldn’t load the research collection.','Please reload the page, or use the official CNS research resource below.')+`<section class="wrap section">${ext('https://exl.cns.utexas.edu/do-research','Visit CNS research resources','button orange')}</section>`;console.error(err);}}
init();
