export const normalize=v=>String(v??'').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'');
export const researchMethods=['Wet lab','Computational','Theoretical','Field research','Mixed methods'];
export const facultyTypes=['Research faculty','Teaching / instructional','Research profile not connected'];
const words=v=>normalize(v).split(/[^a-z0-9]+/).filter(Boolean);
// Short terms must start a word so "rna" doesn't match "journal"; longer terms may match mid-word.
function termScore(ws,t){let best=0;for(const w of ws){if(w===t)return 3;if(w.startsWith(t))best=2;else if(!best&&t.length>=4&&w.includes(t))best=1;}return best;}
export function relevance(fields,q){const terms=words(q);if(!terms.length)return 1;const prepared=fields.map(([v,weight])=>({ws:words([v].flat(Infinity).filter(Boolean).join(' ')),weight}));let score=0;for(const t of terms){let best=0;for(const f of prepared)best=Math.max(best,termScore(f.ws,t)*f.weight);if(!best)return 0;score+=best;}if(terms.length>1){const phrase=' '+terms.join(' ')+' ';for(const f of prepared)if((' '+f.ws.join(' ')+' ').includes(phrase))score+=f.weight*3;}return score;}
export function rank(records,fieldsOf,q){if(!words(q).length)return records;return records.map((r,i)=>({r,i,s:relevance(fieldsOf(r),q)})).filter(x=>x.s>0).sort((a,b)=>b.s-a.s||a.i-b.i).map(x=>x.r);}
const facultyFields=f=>[[f.name,10],[f.labName,6],[f.researchAreas,5],[f.keywords,5],[f.areas,4],[f.methods,3],[f.title,3],[f.majors,2],[f.catalogDepartment,2],[f.appointment,2],[f.summary,1]];
export function prepareData(raw){const enrichment=new Map(raw.faculty_enrichment.map(e=>[e.facultyId,e]));const sources=new Map(raw.faculty_sources.map(s=>[s.facultyId,s]));const catalogFaculty=raw.faculty.map(f=>({...enrichment.get(f.id),...f,profileSources:sources.get(f.id)?.sources||[]}));const faculty=catalogFaculty.filter(f=>f.researchConnected);return {...raw,stories:raw.research_stories,catalogFaculty,faculty,labs:raw.labs.filter(l=>faculty.some(f=>f.id===l.facultyId)),departments:raw.departments.map(d=>({...d,catalogCount:d.count,count:faculty.filter(f=>f.departments.includes(d.name)).length}))};}
export function filterFaculty(records,q={}){const filtered=records.filter(f=>(!q.department||f.departments.includes(q.department))&&(!q.area||f.areas.includes(q.area)||f.researchAreas.includes(q.area))&&(!q.method||f.setting.includes(q.method))&&(!q.type||f.facultyType===q.type)&&(!q.lab||(q.lab==='connected'?!!f.labId:!f.labId))&&(!q.letter||f.alphabetLetter===q.letter)&&(!q.major||f.majors.includes(q.major))).sort((a,b)=>q.sort==='name-desc'?b.catalogOrder-a.catalogOrder:q.sort==='department'||q.view==='departments'?a.department.localeCompare(b.department)||a.catalogOrder-b.catalogOrder:a.catalogOrder-b.catalogOrder);const ranked=rank(filtered,facultyFields,q.q);if(ranked===filtered||!q.sort||q.sort==='relevance')return ranked;const hits=new Set(ranked);return filtered.filter(f=>hits.has(f));}
export function paginate(records,requested=1,size=24){const pages=Math.max(1,Math.ceil(records.length/size));const page=Math.min(pages,Math.max(1,Number.parseInt(requested,10)||1));return {items:records.slice((page-1)*size,page*size),page,pages,total:records.length,start:records.length?(page-1)*size+1:0,end:Math.min(page*size,records.length)};}
export function validateSaved(raw,collections){return Array.isArray(raw)?[...new Set(raw)].filter(key=>typeof key==='string'&&key.length<180&&(()=>{const parts=key.split(':');const[t,id]=parts;return parts.length===2&&Object.hasOwn(collections,t)&&collections[t]?.some(x=>x.id===id);})()):[];}
export function buildEmail({name='',professor='',major='',detail='',skill='',question=''}){return `Subject: A question about your work\n\nDear ${professor.trim()||'[faculty name]'},\n\nMy name is ${name.trim()||'[your name]'}, and I am a ${major.trim()||'[major/year]'} student at UT Austin. I am learning about research connected to my interests.\n\n${detail.trim()||'[Describe a specific research question, paper, or project you read about and explain what interested you.]'}\n\nMy relevant background includes ${skill.trim()||'[a course, project, or skill — describe your experience honestly]'}.\n\n${question.trim()||'[Write one focused question about the research, or ask for a suggested paper or resource to read next.]'}\n\nThank you for your time and consideration.\n\nBest,\n${name.trim()||'[your name]'}`;}
