export const normalize=v=>String(v??'').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'');
export const researchMethods=['Wet lab','Computational','Theoretical','Field research','Mixed methods'];
export const facultyTypes=['Research faculty','Teaching / instructional','Research profile not connected'];
export function matchesQuery(record,q){const haystack=normalize(typeof record==='string'?record:JSON.stringify(record));return normalize(q).trim().split(/\s+/).filter(Boolean).every(t=>haystack.includes(t));}
export function prepareData(raw){const enrichment=new Map(raw.faculty_enrichment.map(e=>[e.facultyId,e]));const sources=new Map(raw.faculty_sources.map(s=>[s.facultyId,s]));const catalogFaculty=raw.faculty.map(f=>({...enrichment.get(f.id),...f,profileSources:sources.get(f.id)?.sources||[]}));const faculty=catalogFaculty.filter(f=>f.researchConnected);return {...raw,stories:raw.research_stories,catalogFaculty,faculty,labs:raw.labs.filter(l=>faculty.some(f=>f.id===l.facultyId)),departments:raw.departments.map(d=>({...d,catalogCount:d.count,count:faculty.filter(f=>f.departments.includes(d.name)).length}))};}
export function filterFaculty(records,q={}){return records.filter(f=>matchesQuery([f.name,f.title,f.appointment,f.catalogDepartment,f.labName,f.summary,f.researchAreas,f.areas,f.methods,f.majors,f.keywords],q.q)&&(!q.department||f.departments.includes(q.department))&&(!q.area||f.areas.includes(q.area)||f.researchAreas.includes(q.area))&&(!q.method||f.setting.includes(q.method))&&(!q.type||f.facultyType===q.type)&&(!q.lab||(q.lab==='connected'?!!f.labId:!f.labId))&&(!q.letter||f.alphabetLetter===q.letter)&&(!q.major||f.majors.includes(q.major))).sort((a,b)=>q.sort==='name-desc'?b.catalogOrder-a.catalogOrder:q.sort==='department'||q.view==='departments'?a.department.localeCompare(b.department)||a.catalogOrder-b.catalogOrder:a.catalogOrder-b.catalogOrder);}
export function paginate(records,requested=1,size=24){const pages=Math.max(1,Math.ceil(records.length/size));const page=Math.min(pages,Math.max(1,Number.parseInt(requested,10)||1));return {items:records.slice((page-1)*size,page*size),page,pages,total:records.length,start:records.length?(page-1)*size+1:0,end:Math.min(page*size,records.length)};}
export function validateSaved(raw,collections){return Array.isArray(raw)?[...new Set(raw)].filter(key=>typeof key==='string'&&key.length<180&&(()=>{const parts=key.split(':');const[t,id]=parts;return parts.length===2&&Object.hasOwn(collections,t)&&collections[t]?.some(x=>x.id===id);})()):[];}
export function buildEmail({name='',professor='',major='',detail='',skill='',question=''}){return `Subject: A question about your work\n\nDear ${professor.trim()||'[faculty name]'},\n\nMy name is ${name.trim()||'[your name]'}, and I am a ${major.trim()||'[major/year]'} student at UT Austin. I am learning about research connected to my interests.\n\n${detail.trim()||'[Describe a specific research question, paper, or project you read about and explain what interested you.]'}\n\nMy relevant background includes ${skill.trim()||'[a course, project, or skill — describe your experience honestly]'}.\n\n${question.trim()||'[Write one focused question about the research, or ask for a suggested paper or resource to read next.]'}\n\nThank you for your time and consideration.\n\nBest,\n${name.trim()||'[your name]'}`;}
